[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/affiliate-marketing-calculator/*"
  to = "https://gregarious-manatee-e6080d.netlify.app/:splat"
  status = 200
