[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/affiliate-marketing-calculator"
  to = "https://imvigour.com/affiliate-marketing-calculator"
  status = 301
  force = true

[[redirects]]
  from = "/affiliate-marketing-calculator/*"
  to = "https://imvigour.com/affiliate-marketing-calculator/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/niche-analyzer/*"
  to = "/niche-analyzer/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
