[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  STANDALONE = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "upgrade-insecure-requests"

[[redirects]]
  from = "https://imvigour.netlify.app/*"
  to = "https://imvigour.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/affiliate-marketing-calculator/*"
  to = "/affiliate-marketing-calculator/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/niche-analyzer/*"
  to = "/niche-analyzer/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
