[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/affiliate-marketing-calculator/assets/*"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/affiliate-marketing-calculator/assets/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/niche-analyzer/assets/*"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/niche-analyzer/assets/*.css"
  [headers.values]
    Content-Type = "text/css"

[[redirects]]
  from = "/affiliate-marketing-calculator/*"
  to = "/affiliate-marketing-calculator/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/niche-analyzer/*"
  to = "/niche-analyzer/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
