[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/affiliate-marketing-calculator/*"
  to = "/affiliate-marketing-calculator/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
